export const NAV_LINKS = [
    {
        id:1,
        name: 'Dashboard',
        superAdminRoutes:[],
        branchManagerRoutes:[],
        authorizerRoutes:[],
        marketerRoutes:[],
        generalScreens:[],
    },
    {
        id:1,
        name: 'Loan Manager',
        superAdminRoutes:[
            {title:'Dashboard',path:'/dashboard',id:'',icon:'bi bi-speedometer2'},
            {title:'Staff Manager',path:'/staff',id:'',icon:''},
            {title:'Customer Manager',path:'/customer',id:'',icon:''},
            {title:'Loan Manager',path:'/loan',id:'',icon:''},
            {title:'Settings',path:'/settings',id:'',icon:''},
        ],
        branchManagerRoutes:[],
        authorizerRoutes:[],
        marketerRoutes:[],
        generalScreens:[],
    },
    {
        id:2,
        name: 'Duplicate Detector',
        superAdminRoutes:[{title:'Dashboard',path:'duplicate/dashboard',id:'',icon:'bi bi-speedometer2'},],
        branchManagerRoutes:[],
        authorizerRoutes:[],
        marketerRoutes:[],
        generalScreens:[],
    },
    {
        id:3,
        name: 'HR Manager',
        superAdminRoutes:[{title:'Dashboard',path:'hr/dashboard',id:'',icon:'bi bi-speedometer2'},],
        branchManagerRoutes:[],
        authorizerRoutes:[],
        marketerRoutes:[],
        generalScreens:[],
    },
    {
        id:4,
        name: 'Accounting',
        superAdminRoutes:[{title:'Dashboard',path:'account/dashboard',id:'',icon:'bi bi-speedometer2'},],
        branchManagerRoutes:[],
        authorizerRoutes:[],
        marketerRoutes:[],
        generalScreens:[],
    },
    {
        id:5,
        name: 'Settings',
        superAdminRoutes:[{title:'Dashboard',path:'settings/dashboard',id:'',icon:'bi bi-speedometer2'},],
        branchManagerRoutes:[],
        authorizerRoutes:[],
        marketerRoutes:[],
        generalScreens:[],
    },
    
]