export const NAV_LINKS = [
    {
        id:1,
        name: 'Dashboard',
        superAdminScreens:[],
        branchManagerScreens:[],
        authorizerScreens:[],
        marketerScreens:[],
        generalScreens:[],
    },
    {
        id:2,
        name: 'Loan Manager',
        superAdminScreens:[],
        branchManagerScreens:[],
        authorizerScreens:[],
        marketerScreens:[],
        generalScreens:[],
    },
    {
        id:3,
        name: 'Duplicate Detector',
        superAdminScreens:[],
        branchManagerScreens:[],
        authorizerScreens:[],
        marketerScreens:[],
        generalScreens:[],
    },
    {
        id:4,
        name: 'HR Manager',
        superAdminScreens:[],
        branchManagerScreens:[],
        authorizerScreens:[],
        marketerScreens:[],
        generalScreens:[],
    },
    {
        id:5,
        name: 'Accounting',
        superAdminScreens:[],
        branchManagerScreens:[],
        authorizerScreens:[],
        marketerScreens:[],
        generalScreens:[],
    },
    {
        id:6,
        name: 'Settings',
        superAdminScreens:[],
        branchManagerScreens:[],
        authorizerScreens:[],
        marketerScreens:[],
        generalScreens:[],
    },
    
]