export const NAV_LINKS = [
    {
        id: 1,
        name: 'Dashboard',
        path: '/dashbaord'
    },
    {
        id: 2,
        name: 'Loan Manager',
        superAdminScreens: [
            { title: 'Dashboard', path: 'loan/dashboard', id: '', icon: 'bi bi-speedometer2' },
            { title: 'Staff Manager', path: '/staff', id: '', icon: '' },
            { title: 'Customer Manager', path: '/customer', id: '', icon: '' },
            { title: 'Loan Manager', path: '/loan', id: '', icon: '' },
            { title: 'Profile', path: '/profile', id: '', icon: '' },
            { title: 'Settings', path: '/settings', id: '', icon: '' },
        ],
        branchManagerScreens: [
            { title: 'Dashboard', path: 'loan/dashboard', id: '', icon: 'bi bi-speedometer2' },
            { title: 'Customer Manager', path: '/customer', id: '', icon: '' },
            { title: 'Loan Manager', path: '/loan', id: '', icon: '' },
            { title: 'Profile', path: '/profile', id: '', icon: '' },
            { title: 'Settings', path: '/settings', id: '', icon: '' },
        ],
        authorizerScreens: [
            { title: 'Dashboard', path: 'loan/dashboard', id: '', icon: 'bi bi-speedometer2' },
            { title: 'Customer Manager', path: '/customer', id: '', icon: '' },
            { title: 'Loan Manager', path: '/loan', id: '', icon: '' },
            { title: 'Profile', path: '/profile', id: '', icon: '' },
            { title: 'Settings', path: '/settings', id: '', icon: '' },
        ],
        marketerScreens: [
            { title: 'Dashboard', path: 'marketer/loan/dashboard', id: '', icon: 'bi bi-speedometer2' },
            { title: 'Customer Manager', path: 'marketer/loan/customer', id: '', icon: '' },
            { title: 'Loan Manager', path: 'marketer/loan', id: '', icon: '' },
            { title: 'Profile', path: 'marketer/profile', id: '', icon: '' },
            { title: 'Settings', path: 'marketer/settings', id: '', icon: '' },
        ],
        generalScreens: [],
    },
    {
        id: 3,
        name: 'Duplicate Detector',
        superAdminScreens: [],
        branchManagerScreens: [],
        authorizerScreens: [],
        marketerScreens: [],
        generalScreens: [],
    },
    {
        id: 4,
        name: 'HR Manager',
        superAdminScreens: [],
        branchManagerScreens: [],
        authorizerScreens: [],
        marketerScreens: [],
        generalScreens: [],
    },
    {
        id: 5,
        name: 'Accounting',
        superAdminScreens: [],
        branchManagerScreens: [],
        authorizerScreens: [],
        marketerScreens: [],
        generalScreens: [],
    },
    {
        id: 6,
        name: 'Settings',
        superAdminScreens: [],
        branchManagerScreens: [],
        authorizerScreens: [],
        marketerScreens: [],
        generalScreens: [],
    },

]